version: "3"
services:
  web:
    build: ./frontend
    image: somkiat/demo-web
    user: "0:0"
    ports:
      - 7999:80
  api:
    build: ./backend
    image: somkiat/demo-api
    user: "0:0"
    ports:
      - 8000:1323
      
  db:
    build: 
      context: ./database
    image: somkiat/demo-db
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5